version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17gavmss325z5"
s3_prefix = "sam-app"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
